import assert from 'node:assert/strict';
import { runOperationalAgents, operationalRoles } from '../lib/agents/operational-agents';
import type { Station } from '../lib/stations';
import type { HealthSnapshot } from '../lib/agents/station-health-policy';

const now = Date.parse('2026-10-03T18:00:00Z');
const station = { station_uuid: 'one', id: 'one', name: 'Example Radio', country: 'Nigeria', country_code: 'NG', city: 'Ibadan', url: 'https://example.com/Audio?Token=A', language: 'English', tags: [], latitude: 7.3775, longitude: 3.947, sourceType: 'radio' } as unknown as Station;
const health: HealthSnapshot = { generatedAt: new Date(now).toISOString(), cursor: 0, records: { [station.url]: { stationId: 'one', url: station.url, checkedAt: new Date(now - 1000).toISOString(), status: 'healthy', reason: 'audio', consecutiveFailures: 0, bytesSampled: 100, responseTimeMs: 10 } } };
const input = { stations: [station, { ...station }], health, workflow: '17 4 * * *\n43 */8 * * *\n29 */8 * * *', now };
const before = JSON.stringify(input);
const report = runOperationalAgents(input);
assert.equal(JSON.stringify(input), before, 'Workers must not mutate catalogs or health');
assert.equal(report.agents.length, 7);
assert.deepEqual(report.agents.map((a) => a.id), operationalRoles.map((a) => a.id));
assert.ok(report.agents.every((a) => a.status === 'completed'));
const analytics = report.agents[1].findings as { catalogStreams: number; freshHealthy: number; unknownHealth: number };
assert.equal(analytics.catalogStreams, 1);
assert.equal(analytics.freshHealthy, 1);
const growth = report.agents[4].findings as { drafts: Array<{ text: string }>; published: boolean };
assert.equal(growth.drafts.length, 1);
assert.equal(growth.published, false);
const changed = runOperationalAgents({ ...input, stations: [{ ...station, url: station.url.toLowerCase() }] });
assert.equal((changed.agents[1].findings as typeof analytics).unknownHealth, 1, 'URL case changes invalidate evidence');
assert.equal((changed.agents[4].findings as typeof growth).drafts.length, 0);
const stale = runOperationalAgents({ ...input, now: now + 49 * 60 * 60 * 1000 });
assert.equal((stale.agents[1].findings as typeof analytics).unknownHealth, 1);
const future = runOperationalAgents({ ...input, now: now - 5000 });
assert.equal((future.agents[1].findings as typeof analytics).unknownHealth, 1);
const missing = runOperationalAgents({ ...input, stations: [], health: { generatedAt: null, cursor: 0, records: {} } });
assert.equal((missing.agents[1].findings as typeof analytics).catalogStreams, 0);
assert.equal((missing.agents[4].findings as typeof growth).drafts.length, 0);
const approx = runOperationalAgents({ ...input, stations: [{ ...station, latitude: undefined, longitude: undefined, city: undefined }] });
assert.equal((approx.agents[0].findings as { issues: unknown[] }).issues.length, 1);
const broken = runOperationalAgents({ ...input, stations: [{ ...station, name: undefined } as unknown as Station] });
assert.equal(broken.agents[5].status, 'failed');
assert.equal(broken.agents[6].status, 'completed', 'One role failing must not stop the supervisor');
assert.deepEqual((broken.agents[6].findings as { failedTasks: string[] }).failedTasks, ['operations-agent']);
console.log('Seven operational roles: evidence, isolation, failure handling and advisory boundaries passed.');
