import assert from 'node:assert/strict';
import { bindPlaybackMediaSession, stationMediaMetadata, type MediaPlayerSnapshot } from '../lib/playback-media-session';
import type { Station } from '../lib/stations';
const jay = { name: 'Jay 101.9 FM Jos', city: 'Jos', country: 'Nigeria' } as Station;
const agidigbo = { ...jay, name: 'Agidigbo 88.7 FM', city: 'Ibadan' };
const doc = Object.assign(new EventTarget(), { title: 'Jay 101.9 FM Jos | WaveAtlas' });
const audio = new EventTarget();
let state: MediaPlayerSnapshot = { current: jay, status: 'playing' };
let listener: (() => void) | undefined;
const actions = new Map<MediaSessionAction, MediaSessionActionHandler | null>();
const session = { metadata: null, playbackState: 'none', setPositionState() {}, setActionHandler(action: MediaSessionAction, handler: MediaSessionActionHandler | null) { actions.set(action, handler); } } as unknown as MediaSession;
class MetadataMock { constructor(data: MediaMetadataInit) { Object.assign(this, data); } }
let plays = 0; let pauses = 0;
const close = bindPlaybackMediaSession({ read: () => state, subscribe: (fn) => { listener = fn; return () => { listener = undefined; }; }, play: () => { plays++; }, pause: () => { pauses++; }, session, Metadata: MetadataMock as unknown as typeof MediaMetadata, document: doc, audio });
assert.equal(session.metadata?.title, jay.name);
state = { current: agidigbo, status: 'buffering' }; listener?.();
assert.equal(session.metadata?.title, agidigbo.name);
assert.equal(doc.title, 'Agidigbo 88.7 FM | WaveAtlas');
assert.equal(session.playbackState, 'paused');
state.status = 'playing'; audio.dispatchEvent(new Event('playing'));
assert.equal(session.playbackState, 'playing');
// A delayed event from the old stream must read the current station, never a captured station.
audio.dispatchEvent(new Event('loadedmetadata'));
assert.equal(session.metadata?.title, agidigbo.name);
doc.dispatchEvent(new Event('visibilitychange')); assert.equal(session.metadata?.artist, 'Ibadan, Nigeria');
actions.get('play')?.({ action: 'play' }); actions.get('pause')?.({ action: 'pause' });
assert.equal(plays, 1); assert.equal(pauses, 1);
state.status = 'paused'; listener?.(); assert.equal(session.metadata?.title, agidigbo.name);
state.status = 'failed'; listener?.(); assert.equal(session.metadata, null); assert.equal(session.playbackState, 'none'); assert.ok(!doc.title.includes('Jay'));
close(); assert.equal(listener, undefined); assert.ok([...actions.values()].every((handler) => handler === null));
audio.dispatchEvent(new Event('playing')); assert.equal(session.metadata, null);
assert.equal(doc.title, 'Jay 101.9 FM Jos | WaveAtlas');
const unsupportedClose = bindPlaybackMediaSession({ read: () => ({ current: agidigbo, status: 'playing' }), subscribe: () => () => {}, play() {}, pause() {}, document: doc, audio });
assert.equal(doc.title, 'Agidigbo 88.7 FM | WaveAtlas'); unsupportedClose();
const partial = { setActionHandler() { throw new Error('Unsupported'); }, setPositionState() { throw new Error('Unsupported'); } } as unknown as MediaSession;
const partialClose = bindPlaybackMediaSession({ read: () => state, subscribe: () => () => {}, play() {}, pause() {}, session: partial, document: doc, audio }); partialClose();
const journey = { ...agidigbo, sourceType: 'geoaudio', geoAudio: { currentTrackTitle: 'Work On Me', artist: 'Carine Sanadina', albumTitle: 'Journey' } } as Station;
assert.equal(stationMediaMetadata(journey).title, 'Work On Me');
console.log('Media session: station switching, late events, foreground refresh, controls, cleanup and unsupported browsers passed.');
