'use client';
import { motion } from 'framer-motion';
import { Globe2, Heart, MapPin, Play, Radar, ScanLine, Search, Share2, Signal, SkipForward, Volume2 } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { create } from 'zustand';
import type { Station } from '@/lib/stations';

type PlayerState = { current?: Station; playing:boolean; volume:number; setStation:(s:Station)=>void; toggle:()=>void; setVolume:(n:number)=>void };
const usePlayer = create<PlayerState>((set)=>({ playing:false, volume:.82, setStation:(current)=>set({current, playing:true}), toggle:()=>set(s=>({playing:!s.playing})), setVolume:(volume)=>set({volume}) }));

function AudioEngine(){ const {current, playing, volume} = usePlayer(); const audio = useRef<HTMLAudioElement|null>(null); useEffect(()=>{ audio.current = new Audio(); audio.current.crossOrigin = 'anonymous'; return ()=>{ audio.current?.pause(); }; },[]); useEffect(()=>{ const a=audio.current; if(!a||!current) return; const prior=a.volume; const fade=setInterval(()=>{ a.volume=Math.max(0,a.volume-.12); if(a.volume<=.02){ clearInterval(fade); a.src=current.url; a.load(); a.volume=0; if(playing) a.play().catch(()=>{}); const up=setInterval(()=>{ a.volume=Math.min(volume,a.volume+.1); if(a.volume>=volume) clearInterval(up); },45); } },35); return ()=>clearInterval(fade); },[current, playing, volume]); useEffect(()=>{ const a=audio.current; if(!a) return; a.volume=volume; if(playing) a.play().catch(()=>{}); else a.pause(); },[playing, volume]); return null; }

function SignalMeter({score}:{score:number}){ return <div className="flex h-14 items-end gap-1">{[28,42,56,70,84].map((h,i)=><motion.span key={h} className="w-2 rounded-full bg-radio" animate={{height: score/20>i? h: 12, opacity: score/20>i?.95:.28}} transition={{repeat:Infinity, repeatType:'mirror', duration:.7+i*.08}} />)}</div>; }

function RadioDial({stations}:{stations:Station[]}){ const [index,setIndex]=useState(0); const current=stations[index] ?? stations[0]; const setStation=usePlayer(s=>s.setStation); const ticks=useMemo(()=>Array.from({length:41},(_,i)=>i),[]); useEffect(()=>{ if(current) setStation(current); },[current, setStation]); const tune=(delta:number)=>{ const next=(index+delta+stations.length)%stations.length; setIndex(next); setStation(stations[next]); }; return <section className="glass overflow-hidden rounded-[2rem] p-5 shadow-glow md:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center"><div className="flex-1"><p className="mb-3 font-mono text-xs uppercase tracking-[.35em] text-gold">Global terrestrial dial</p><h1 className="text-4xl font-black tracking-tight md:text-7xl">Tune the World.</h1><p className="mt-4 max-w-2xl text-ivory/70">Spin across active stations, languages, countries, and cultures with the feel of a real analog receiver connected to the planet.</p></div><button onClick={()=>tune(1)} className="min-h-14 rounded-full bg-gold px-6 font-bold text-midnight shadow-lg shadow-gold/20"><SkipForward className="mr-2 inline"/> Next live signal</button></div><div className="mt-8 rounded-[1.5rem] border border-white/10 bg-midnight/70 p-4"><div onPointerDown={(e)=>{(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}} onPointerMove={(e)=>{ if(e.buttons) tune(e.movementX<0?1:-1)}} className="dial-texture relative h-36 cursor-grab select-none overflow-hidden rounded-3xl border border-sky/20"><div className="absolute inset-x-1/2 top-0 h-full w-px bg-gold shadow-[0_0_24px_#D6A84F]" /> <div className="flex h-full items-end justify-around px-6 pb-6">{ticks.map(t=><span key={t} className={`w-px rounded bg-ivory/${t%5===0?'80 h-20':'35 h-10'}`} />)}</div><motion.div className="absolute left-1/2 top-7 -translate-x-1/2 rounded-full border border-gold/50 bg-gold/10 px-4 py-2 font-mono text-sm text-gold" key={current?.station_uuid} initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}}>{(88+index*.7).toFixed(1)} WA</motion.div></div></div></section>; }
function NowPlaying({station}:{station:Station}){ const {playing,toggle,volume,setVolume}=usePlayer(); return <aside className="glass rounded-[2rem] p-6"><div className="flex items-start justify-between"><div><p className="font-mono text-xs uppercase tracking-[.3em] text-radio">Now playing</p><h2 className="mt-2 text-3xl font-black">{station.name}</h2><p className="mt-2 flex items-center gap-2 text-ivory/70"><MapPin size={16}/>{station.country} · {station.language}</p></div><SignalMeter score={station.health_score}/></div><div className="my-6 grid grid-cols-3 gap-3 text-center font-mono text-xs"><span className="rounded-2xl bg-white/5 p-3">{station.codec}</span><span className="rounded-2xl bg-white/5 p-3">{station.bitrate || 'Live'} kbps</span><span className="rounded-2xl bg-white/5 p-3 text-radio">{station.health_score}% signal</span></div><div className="flex flex-wrap items-center gap-3"><button onClick={toggle} className="min-h-14 rounded-full bg-radio px-7 font-bold text-midnight"><Play className="mr-2 inline"/>{playing?'Pause':'Play'}</button><button className="rounded-full border border-white/15 p-4"><Heart/></button><button className="rounded-full border border-white/15 p-4"><Share2/></button><Volume2/><input aria-label="Volume" type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></div></aside>; }

export default function WaveAtlasApp({stations}:{stations:Station[]}){ const current=usePlayer(s=>s.current) ?? stations[0]; const [query,setQuery]=useState(''); return <main className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top,#12385a,transparent_35%),#07111F] p-4 pb-28 md:p-8"><AudioEngine/><nav className="mx-auto mb-6 flex max-w-7xl items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-2xl bg-sky/15 p-3 text-sky"><Globe2/></div><b className="text-xl">WaveAtlas</b></div><div className="hidden gap-2 md:flex">{['Dial','Atlas','Discover','Favorites'].map(x=><span className="rounded-full border border-white/10 px-4 py-2 text-sm text-ivory/70" key={x}>{x}</span>)}</div></nav><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[1.3fr_.7fr]"><RadioDial stations={stations}/><NowPlaying station={current}/></div><section className="mx-auto mt-6 grid max-w-7xl gap-6 lg:grid-cols-3"><div className="glass rounded-[2rem] p-6 lg:col-span-2"><div className="flex gap-3"><Search className="text-sky"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: play Nigerian gospel radio" className="w-full bg-transparent outline-none placeholder:text-ivory/40"/></div><div className="mt-5 grid gap-3 md:grid-cols-2">{stations.slice(0,6).filter(s=>!query||`${s.name} ${s.country} ${s.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).map(s=><button key={s.id} onClick={()=>usePlayer.getState().setStation(s)} className="rounded-2xl border border-white/10 bg-white/5 p-4 text-left hover:border-gold/50"><b>{s.name}</b><p className="mt-1 text-sm text-ivory/60">{s.country} · {s.tags.slice(0,3).join(', ')}</p></button>)}</div></div><div className="glass rounded-[2rem] p-6"><p className="font-mono text-xs uppercase tracking-[.3em] text-gold">Atlas scan</p><div className="mt-5 aspect-video rounded-3xl border border-sky/20 bg-[radial-gradient(circle,#38BDF833_1px,transparent_2px)] [background-size:28px_28px] p-5"><Radar className="animate-pulse text-sky"/><p className="mt-16 text-sm text-ivory/60">Country clusters ready · {stations.length} validated signals</p></div><button className="mt-4 w-full rounded-full border border-radio/30 py-3 text-radio"><ScanLine className="mr-2 inline"/>Start scan mode</button></div></section></main>; }
