'use client';
import 'maplibre-gl/dist/maplibre-gl.css';
import maplibregl, { type Map, type Marker } from 'maplibre-gl';
import { motion } from 'framer-motion';
import { Globe2, Heart, MapPin, Play, Radar, ScanLine, Search, Share2, Signal, SkipForward, Volume2 } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { create } from 'zustand';
import type { Station } from '@/lib/stations';

type GeoPoint = { lat: number; lng: number; label: string; precision: 'station' | 'city' | 'country'; tone: 'green-gold' | 'blue-gold' | 'radio-gold' };

type PlayerState = { current?: Station; playing:boolean; volume:number; setStation:(s:Station)=>void; toggle:()=>void; setVolume:(n:number)=>void };
const usePlayer = create<PlayerState>((set)=>({ playing:false, volume:.82, setStation:(current)=>set({current, playing:true}), toggle:()=>set(s=>({playing:!s.playing})), setVolume:(volume)=>set({volume}) }));

const countryFallbacks: Record<string, Omit<GeoPoint, 'label' | 'precision'>> = {
  NG: { lat: 9.082, lng: 8.6753, tone: 'green-gold' },
  AE: { lat: 25.2048, lng: 55.2708, tone: 'blue-gold' },
  FR: { lat: 46.2276, lng: 2.2137, tone: 'radio-gold' },
  GB: { lat: 55.3781, lng: -3.436, tone: 'radio-gold' },
  US: { lat: 39.8283, lng: -98.5795, tone: 'radio-gold' },
  GH: { lat: 7.9465, lng: -1.0232, tone: 'green-gold' },
  BR: { lat: -14.235, lng: -51.9253, tone: 'radio-gold' },
  JP: { lat: 36.2048, lng: 138.2529, tone: 'radio-gold' }
};

const cityFallbacks: Record<string, Omit<GeoPoint, 'label' | 'precision'>> = {
  lagos: { lat: 6.5244, lng: 3.3792, tone: 'green-gold' },
  abuja: { lat: 9.0765, lng: 7.3986, tone: 'green-gold' },
  dubai: { lat: 25.2048, lng: 55.2708, tone: 'blue-gold' },
  paris: { lat: 48.8566, lng: 2.3522, tone: 'radio-gold' },
  london: { lat: 51.5072, lng: -0.1276, tone: 'radio-gold' },
  'new york': { lat: 40.7128, lng: -74.006, tone: 'radio-gold' }
};

function CountryFallbackResolver(station: Station): GeoPoint {
  if (typeof station.latitude === 'number' && typeof station.longitude === 'number') return { lat: station.latitude, lng: station.longitude, label: station.state || station.country, precision: 'station', tone: station.country_code === 'NG' ? 'green-gold' : station.country_code === 'AE' ? 'blue-gold' : 'radio-gold' };
  const city = cityFallbacks[(station.state || '').toLowerCase()] || cityFallbacks[station.country.toLowerCase()];
  if (city) return { ...city, label: station.state || station.country, precision: 'city' };
  const country = countryFallbacks[station.country_code] || countryFallbacks.US;
  return { ...country, label: station.country, precision: 'country' };
}

function AudioEngine(){ const {current, playing, volume} = usePlayer(); const audio = useRef<HTMLAudioElement|null>(null); useEffect(()=>{ audio.current = new Audio(); audio.current.crossOrigin = 'anonymous'; return ()=>{ audio.current?.pause(); }; },[]); useEffect(()=>{ const a=audio.current; if(!a||!current) return; const fade=setInterval(()=>{ a.volume=Math.max(0,a.volume-.12); if(a.volume<=.02){ clearInterval(fade); a.src=current.url; a.load(); a.volume=0; if(playing) a.play().catch(()=>{}); const up=setInterval(()=>{ a.volume=Math.min(volume,a.volume+.1); if(a.volume>=volume) clearInterval(up); },45); } },35); return ()=>clearInterval(fade); },[current, playing, volume]); useEffect(()=>{ const a=audio.current; if(!a) return; a.volume=volume; if(playing) a.play().catch(()=>{}); else a.pause(); },[playing, volume]); return null; }

function SignalMeter({score}:{score:number}){ return <div className="flex h-14 items-end gap-1">{[28,42,56,70,84].map((h,i)=><motion.span key={h} className="w-2 rounded-full bg-radio" animate={{height: score/20>i? h: 12, opacity: score/20>i?.95:.28}} transition={{repeat:Infinity, repeatType:'mirror', duration:.7+i*.08}} />)}</div>; }

function StationPulseMarker({ geo, playing }: { geo: GeoPoint; playing: boolean }) { return <div className={`station-pulse-marker tone-${geo.tone} ${playing ? 'is-playing' : ''}`} aria-label={`${geo.label} station pulse`}><span className="station-pulse-ring"/><span className="station-pulse-dot"/></div>; }

function MapFlyToController({ map, marker, station, playing }: { map: Map | null; marker: Marker | null; station: Station; playing: boolean }) { const geo = useMemo(()=>CountryFallbackResolver(station),[station]); useEffect(()=>{ if(!map||!marker) return; marker.setLngLat([geo.lng, geo.lat]); map.flyTo({ center:[geo.lng, geo.lat], zoom: geo.precision === 'station' ? 7 : 4.2, speed: .8, curve: 1.35, essential: true }); },[geo,map,marker]); useEffect(()=>{ marker?.getElement().classList.toggle('is-playing', playing); },[marker, playing]); return null; }

function NowPlayingGeoCard({ station, geo, playing }: { station: Station; geo: GeoPoint; playing: boolean }) { return <div className="absolute bottom-4 left-4 right-4 rounded-3xl border border-white/15 bg-midnight/85 p-4 shadow-glow backdrop-blur"><p className="font-mono text-[10px] uppercase tracking-[.28em] text-gold">Live station geo pulse</p><div className="mt-2 flex items-start justify-between gap-3"><div><b className="text-lg">{station.name}</b><p className="mt-1 text-sm text-ivory/70">{station.country} · {station.language || 'Unknown language'}</p><p className="mt-1 text-xs text-ivory/50">{geo.precision === 'station' ? 'Radio Browser coordinates' : `${geo.precision} fallback`} · {geo.lat.toFixed(3)}, {geo.lng.toFixed(3)}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${playing ? 'bg-radio text-midnight' : 'bg-white/10 text-ivory/60'}`}>{playing ? 'Beeping' : 'Paused'}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><motion.div className="h-full bg-radio" animate={{ width: `${station.health_score}%` }} /></div><p className="mt-1 text-right font-mono text-xs text-radio">{station.health_score}% stream health</p></div>; }

function WaveAtlasMap({ station }: { station: Station }) { const playing = usePlayer(s=>s.playing); const container = useRef<HTMLDivElement|null>(null); const [map,setMap]=useState<Map|null>(null); const [marker,setMarker]=useState<Marker|null>(null); const geo=useMemo(()=>CountryFallbackResolver(station),[station]); const initialGeo = useRef(geo); useEffect(()=>{ if(!container.current) return; const start = initialGeo.current; const m = new maplibregl.Map({ container: container.current, style: 'https://demotiles.maplibre.org/style.json', center:[start.lng, start.lat], zoom: 3.2, attributionControl:false }); m.addControl(new maplibregl.AttributionControl({ compact:true })); const markerRoot = document.createElement('div'); markerRoot.className = `station-pulse-marker tone-${start.tone} is-playing`; markerRoot.innerHTML = '<span class="station-pulse-ring"></span><span class="station-pulse-dot"></span>';  const mk = new maplibregl.Marker({ element: markerRoot, anchor:'center' }).setLngLat([start.lng, start.lat]).addTo(m); setMap(m); setMarker(mk); return ()=>m.remove(); },[]); useEffect(()=>{ if(!marker) return; const element = marker.getElement(); element.className = `station-pulse-marker tone-${geo.tone} ${playing ? 'is-playing' : ''}`; element.innerHTML = '<span class="station-pulse-ring"></span><span class="station-pulse-dot"></span>'; },[geo.tone, marker, playing]); return <div className="glass relative min-h-[28rem] overflow-hidden rounded-[2rem]"><div ref={container} className="absolute inset-0"/><MapFlyToController map={map} marker={marker} station={station} playing={playing}/><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_center,transparent,rgba(7,17,31,.58))]"/><NowPlayingGeoCard station={station} geo={geo} playing={playing}/><div className="sr-only"><StationPulseMarker geo={geo} playing={playing}/></div></div>; }

function RadioDial({stations}:{stations:Station[]}){ const [index,setIndex]=useState(0); const current=stations[index] ?? stations[0]; const setStation=usePlayer(s=>s.setStation); const ticks=useMemo(()=>Array.from({length:41},(_,i)=>i),[]); useEffect(()=>{ if(current) setStation(current); },[current, setStation]); const tune=(delta:number)=>{ const next=(index+delta+stations.length)%stations.length; setIndex(next); setStation(stations[next]); }; return <section className="glass overflow-hidden rounded-[2rem] p-5 shadow-glow md:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center"><div className="flex-1"><p className="mb-3 font-mono text-xs uppercase tracking-[.35em] text-gold">Global terrestrial dial</p><h1 className="text-4xl font-black tracking-tight md:text-7xl">Tune the World.</h1><p className="mt-4 max-w-2xl text-ivory/70">Spin across active stations, languages, countries, and cultures with the feel of a real analog receiver connected to the planet.</p></div><button onClick={()=>tune(1)} className="min-h-14 rounded-full bg-gold px-6 font-bold text-midnight shadow-lg shadow-gold/20"><SkipForward className="mr-2 inline"/> Next live signal</button></div><div className="mt-8 rounded-[1.5rem] border border-white/10 bg-midnight/70 p-4"><div onPointerDown={(e)=>{(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}} onPointerMove={(e)=>{ if(e.buttons) tune(e.movementX<0?1:-1)}} className="dial-texture relative h-36 cursor-grab select-none overflow-hidden rounded-3xl border border-sky/20"><div className="absolute inset-x-1/2 top-0 h-full w-px bg-gold shadow-[0_0_24px_#D6A84F]" /> <div className="flex h-full items-end justify-around px-6 pb-6">{ticks.map(t=><span key={t} className={`w-px rounded bg-ivory/${t%5===0?'80 h-20':'35 h-10'}`} />)}</div><motion.div className="absolute left-1/2 top-7 -translate-x-1/2 rounded-full border border-gold/50 bg-gold/10 px-4 py-2 font-mono text-sm text-gold" key={current?.station_uuid} initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}}>{(88+index*.7).toFixed(1)} WA</motion.div></div></div></section>; }
function NowPlaying({station}:{station:Station}){ const {playing,toggle,volume,setVolume}=usePlayer(); return <aside className="glass rounded-[2rem] p-6"><div className="flex items-start justify-between"><div><p className="font-mono text-xs uppercase tracking-[.3em] text-radio">Now playing</p><h2 className="mt-2 text-3xl font-black">{station.name}</h2><p className="mt-2 flex items-center gap-2 text-ivory/70"><MapPin size={16}/>{station.country} · {station.language}</p></div><SignalMeter score={station.health_score}/></div><div className="my-6 grid grid-cols-3 gap-3 text-center font-mono text-xs"><span className="rounded-2xl bg-white/5 p-3">{station.codec}</span><span className="rounded-2xl bg-white/5 p-3">{station.bitrate || 'Live'} kbps</span><span className="rounded-2xl bg-white/5 p-3 text-radio">{station.health_score}% signal</span></div><div className="flex flex-wrap items-center gap-3"><button onClick={toggle} className="min-h-14 rounded-full bg-radio px-7 font-bold text-midnight"><Play className="mr-2 inline"/>{playing?'Pause':'Play'}</button><button className="rounded-full border border-white/15 p-4"><Heart/></button><button className="rounded-full border border-white/15 p-4"><Share2/></button><Volume2/><input aria-label="Volume" type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></div></aside>; }

export default function WaveAtlasApp({stations}:{stations:Station[]}){ const current=usePlayer(s=>s.current) ?? stations[0]; const [query,setQuery]=useState(''); return <main className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top,#12385a,transparent_35%),#07111F] p-4 pb-28 md:p-8"><AudioEngine/><nav className="mx-auto mb-6 flex max-w-7xl items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-2xl bg-sky/15 p-3 text-sky"><Globe2/></div><b className="text-xl">WaveAtlas</b></div><div className="hidden gap-2 md:flex">{['Dial','Atlas','Discover','Favorites'].map(x=><span className="rounded-full border border-white/10 px-4 py-2 text-sm text-ivory/70" key={x}>{x}</span>)}</div></nav><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[1.3fr_.7fr]"><RadioDial stations={stations}/><NowPlaying station={current}/></div><section className="mx-auto mt-6 grid max-w-7xl gap-6 lg:grid-cols-3"><div className="lg:col-span-2"><WaveAtlasMap station={current}/></div><div className="glass rounded-[2rem] p-6"><p className="font-mono text-xs uppercase tracking-[.3em] text-gold">Atlas scan</p><div className="mt-5 aspect-video rounded-3xl border border-sky/20 bg-[radial-gradient(circle,#38BDF833_1px,transparent_2px)] [background-size:28px_28px] p-5"><Radar className="animate-pulse text-sky"/><p className="mt-16 text-sm text-ivory/60">Country clusters ready · {stations.length} validated signals</p></div><button className="mt-4 w-full rounded-full border border-radio/30 py-3 text-radio"><ScanLine className="mr-2 inline"/>Start scan mode</button></div><div className="glass rounded-[2rem] p-6 lg:col-span-3"><div className="flex gap-3"><Search className="text-sky"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: play Nigerian gospel radio" className="w-full bg-transparent outline-none placeholder:text-ivory/40"/></div><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{stations.slice(0,6).filter(s=>!query||`${s.name} ${s.country} ${s.state} ${s.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).map(s=><button key={s.id} onClick={()=>usePlayer.getState().setStation(s)} className="rounded-2xl border border-white/10 bg-white/5 p-4 text-left hover:border-gold/50"><b>{s.name}</b><p className="mt-1 text-sm text-ivory/60">{s.country} · {s.tags.slice(0,3).join(', ')}</p></button>)}</div></div></section></main>; }
