export type Station = { id:string; station_uuid:string; name:string; url:string; homepage?:string; favicon?:string; country:string; country_code:string; state?:string; language:string; tags:string[]; codec:string; bitrate:number; latitude?:number; longitude?:number; votes:number; click_count:number; health_score:number; is_active:boolean; last_checked_at:string; failure_count:number; response_time_ms:number; };

type RadioBrowserStation = Partial<Record<'stationuuid'|'name'|'url_resolved'|'url'|'homepage'|'favicon'|'country'|'countrycode'|'state'|'language'|'tags'|'codec', string>> & { bitrate?: number; geo_lat?: number; geo_long?: number; votes?: number; clickcount?: number; lastcheckok?: number; lastchecktime_iso8601?: string; clicktrend?: number };

const API_BASE = process.env.RADIO_BROWSER_API_BASE ?? 'https://de1.api.radio-browser.info/json';
const UA = 'WaveAtlas/1.0 (global-radio-discovery)';

const fallbackStations: Station[] = [
  { id:'fip-paris', station_uuid:'fip-paris', name:'FIP', url:'https://icecast.radiofrance.fr/fip-midfi.mp3', homepage:'https://www.radiofrance.fr/fip', favicon:'', country:'France', country_code:'FR', state:'Paris', language:'French', tags:['jazz','world','eclectic'], codec:'MP3', bitrate:128, latitude:48.8566, longitude:2.3522, votes:26000, click_count:82000, health_score:96, is_active:true, last_checked_at:new Date().toISOString(), failure_count:0, response_time_ms:180 },
  { id:'bbc-world', station_uuid:'bbc-world', name:'BBC World Service', url:'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service', homepage:'https://www.bbc.co.uk/worldserviceradio', favicon:'', country:'United Kingdom', country_code:'GB', state:'London', language:'English', tags:['news','talk','world'], codec:'MP3', bitrate:96, latitude:51.5072, longitude:-0.1276, votes:31000, click_count:99000, health_score:94, is_active:true, last_checked_at:new Date().toISOString(), failure_count:0, response_time_ms:220 },
  { id:'wnyc', station_uuid:'wnyc', name:'WNYC FM', url:'https://fm939.wnyc.org/wnycfm', homepage:'https://www.wnyc.org/', favicon:'', country:'United States', country_code:'US', state:'New York', language:'English', tags:['news','public radio','new york'], codec:'MP3', bitrate:128, latitude:40.7128, longitude:-74.006, votes:18000, click_count:65000, health_score:91, is_active:true, last_checked_at:new Date().toISOString(), failure_count:0, response_time_ms:260 },
  { id:'lagos-gospel', station_uuid:'lagos-gospel', name:'Lagos Gospel Radio', url:'https://stream.zeno.fm/0r0xa792kwzuv', homepage:'', favicon:'', country:'Nigeria', country_code:'NG', state:'Lagos', language:'English, Yoruba', tags:['gospel','afrobeats','faith'], codec:'MP3', bitrate:128, latitude:6.5244, longitude:3.3792, votes:8200, click_count:22000, health_score:88, is_active:true, last_checked_at:new Date().toISOString(), failure_count:1, response_time_ms:320 },
  { id:'dubai-eye', station_uuid:'dubai-eye', name:'Dubai Eye 103.8', url:'https://stream.radiojar.com/eye1038', homepage:'https://www.dubaieye1038.com/', favicon:'', country:'United Arab Emirates', country_code:'AE', state:'Dubai', language:'English, Arabic', tags:['dubai','business','talk'], codec:'MP3', bitrate:128, latitude:25.2048, longitude:55.2708, votes:7600, click_count:21000, health_score:87, is_active:true, last_checked_at:new Date().toISOString(), failure_count:0, response_time_ms:300 }
];

function normalize(s: RadioBrowserStation): Station { const ok = s.lastcheckok === 1; const bitrate = s.bitrate ?? 0; const votes = s.votes ?? 0; const click_count = s.clickcount ?? 0; const health_score = Math.min(99, Math.max(50, (ok ? 72 : 48) + Math.min(18, bitrate/16) + Math.min(9, votes/1200))); return { id:s.stationuuid ?? crypto.randomUUID(), station_uuid:s.stationuuid ?? '', name:s.name ?? 'Unknown station', url:s.url_resolved || s.url || '', homepage:s.homepage, favicon:s.favicon, country:s.country ?? 'Global', country_code:s.countrycode ?? 'UN', state:s.state, language:s.language ?? 'Unknown', tags:(s.tags ?? '').split(',').map(t=>t.trim()).filter(Boolean).slice(0,6), codec:s.codec ?? 'Unknown', bitrate, latitude:s.geo_lat, longitude:s.geo_long, votes, click_count, health_score:Math.round(health_score), is_active:ok, last_checked_at:s.lastchecktime_iso8601 ?? new Date().toISOString(), failure_count:ok ? 0 : 1, response_time_ms:180 + Math.round(Math.random()*420) }; }

export async function fetchStations(params: Record<string,string|undefined> = {}): Promise<Station[]> { const query = new URLSearchParams({ hidebroken:'true', limit: params.limit ?? '36', order:'clickcount', reverse:'true' }); if(params.country) query.set('country', params.country); if(params.language) query.set('language', params.language); if(params.tag) query.set('tag', params.tag); if(params.name) query.set('name', params.name); try { const res = await fetch(`${API_BASE}/stations/search?${query}`, { headers:{ 'User-Agent': UA }, next:{ revalidate: 300 } }); if(!res.ok) throw new Error(`Radio Browser ${res.status}`); const data = await res.json() as RadioBrowserStation[]; const stations = data.map(normalize).filter(s=>s.url && s.is_active).sort((a,b)=>b.health_score-a.health_score); return stations.length ? stations : fallbackStations; } catch { return fallbackStations; } }

export async function validateStream(url: string) { const started = Date.now(); const controller = new AbortController(); const timer = setTimeout(()=>controller.abort(), 7000); try { if(!/^https?:\/\//i.test(url)) throw new Error('Unsafe stream URL'); const res = await fetch(url, { method:'HEAD', signal:controller.signal, redirect:'follow' }); const type = res.headers.get('content-type') ?? ''; const playable = res.ok && /(audio|mpeg|ogg|aac|mp3|x-scpls|octet-stream)/i.test(type); return { is_active: playable, health_score: playable ? 90 : 35, response_time_ms: Date.now()-started, failure_count: playable ? 0 : 1, content_type:type, last_checked_at:new Date().toISOString() }; } catch { return { is_active:false, health_score:10, response_time_ms:Date.now()-started, failure_count:1, content_type:'unknown', last_checked_at:new Date().toISOString() }; } finally { clearTimeout(timer); } }

export function discoverIntent(query: string) { const q = query.toLowerCase(); const countries = ['nigeria','dubai','united arab emirates','france','united states','ghana','brazil','japan','united kingdom']; const tags = ['gospel','jazz','news','talk','afrobeats','classical','reggae']; return { country: countries.find(c=>q.includes(c)), tag: tags.find(t=>q.includes(t)), language: q.includes('french')?'french':q.includes('english')?'english':undefined } as Record<string,string|undefined>; }
