export type Station = { id:string; station_uuid:string; name:string; url:string; homepage?:string; favicon?:string; country:string; country_code:string; state?:string; language:string; tags:string[]; codec:string; bitrate:number; latitude?:number; longitude?:number; votes:number; click_count:number; health_score:number; is_active:boolean; last_checked_at:string; failure_count:number; response_time_ms:number; };
export type CountryResult = { name:string; code:string; flag:string; centroid:{ lat:number; lng:number }; station_count:number };

type RadioBrowserStation = Partial<Record<'stationuuid'|'name'|'url_resolved'|'url'|'homepage'|'favicon'|'country'|'countrycode'|'state'|'language'|'tags'|'codec', string>> & { bitrate?: number; geo_lat?: number; geo_long?: number; votes?: number; clickcount?: number; lastcheckok?: number; lastchecktime_iso8601?: string; clicktrend?: number };
type RadioBrowserCountry = { name?: string; iso_3166_1?: string; stationcount?: number };

const API_BASE = process.env.RADIO_BROWSER_API_BASE ?? 'https://de1.api.radio-browser.info/json';
const UA = 'WaveAtlas/1.0 (global-radio-discovery)';
const cache = new Map<string, { expires:number; value: unknown }>();

const countryCentroids: Record<string, { lat:number; lng:number }> = {
  NG:{lat:9.082,lng:8.6753}, DE:{lat:51.1657,lng:10.4515}, GH:{lat:7.9465,lng:-1.0232}, FR:{lat:46.2276,lng:2.2137}, AE:{lat:23.4241,lng:53.8478}, US:{lat:39.8283,lng:-98.5795}, BR:{lat:-14.235,lng:-51.9253}, GB:{lat:55.3781,lng:-3.436}, JP:{lat:36.2048,lng:138.2529}, ZA:{lat:-30.5595,lng:22.9375}, CA:{lat:56.1304,lng:-106.3468}, IN:{lat:20.5937,lng:78.9629}, AU:{lat:-25.2744,lng:133.7751}, MX:{lat:23.6345,lng:-102.5528}, ES:{lat:40.4637,lng:-3.7492}, IT:{lat:41.8719,lng:12.5674}
};
const aliases: Record<string, string> = { dubai:'AE', uae:'AE', 'united arab emirates':'AE', america:'US', usa:'US', 'united states':'US', uk:'GB', britain:'GB', england:'GB', germany:'DE', nigeria:'NG', ghana:'GH', france:'FR', brazil:'BR' };
const fallbackStations: Station[] = [
  { id:'fip-paris', station_uuid:'fip-paris', name:'FIP', url:'https://icecast.radiofrance.fr/fip-midfi.mp3', homepage:'https://www.radiofrance.fr/fip', favicon:'', country:'France', country_code:'FR', state:'Paris', language:'French', tags:['jazz','world','eclectic'], codec:'MP3', bitrate:128, latitude:48.8566, longitude:2.3522, votes:26000, click_count:82000, health_score:96, is_active:true, last_checked_at:new Date().toISOString(), failure_count:0, response_time_ms:180 }
];

function flagFor(code = '') { return code.length === 2 ? String.fromCodePoint(...code.toUpperCase().split('').map((c)=>127397+c.charCodeAt(0))) : '🌐'; }
async function cached<T>(key:string, ttlMs:number, fn:()=>Promise<T>): Promise<T> { const hit=cache.get(key); if(hit && hit.expires>Date.now()) return hit.value as T; const value=await fn(); cache.set(key,{value,expires:Date.now()+ttlMs}); return value; }
function normalize(s: RadioBrowserStation): Station { const ok = s.lastcheckok !== 0; const bitrate = s.bitrate ?? 0; const votes = s.votes ?? 0; const click_count = s.clickcount ?? 0; const health_score = Math.min(99, Math.max(35, (ok ? 72 : 42) + Math.min(18, bitrate/16) + Math.min(9, votes/1200))); return { id:s.stationuuid ?? crypto.randomUUID(), station_uuid:s.stationuuid ?? '', name:s.name ?? 'Unknown station', url:s.url_resolved || s.url || '', homepage:s.homepage, favicon:s.favicon, country:s.country ?? 'Global', country_code:(s.countrycode ?? 'UN').toUpperCase(), state:s.state, language:s.language ?? 'Unknown', tags:(s.tags ?? '').split(',').map(t=>t.trim()).filter(Boolean).slice(0,8), codec:s.codec ?? 'Unknown', bitrate, latitude:s.geo_lat, longitude:s.geo_long, votes, click_count, health_score:Math.round(health_score), is_active:ok, last_checked_at:s.lastchecktime_iso8601 ?? new Date().toISOString(), failure_count:ok ? 0 : 1, response_time_ms:180 + Math.round(Math.random()*420) }; }
function sortStations(a:Station,b:Station){ return Number(b.is_active)-Number(a.is_active) || b.votes-a.votes || b.click_count-a.click_count || b.bitrate-a.bitrate; }

export async function fetchStations(params: Record<string,string|undefined> = {}): Promise<Station[]> { const limit=params.limit ?? '50'; const offset=params.offset ?? '0'; const query = new URLSearchParams({ hidebroken:'true', limit, offset, order: params.order ?? 'votes', reverse:'true' }); if(params.country) query.set('country', params.country); if(params.countryCode) query.set('countrycode', params.countryCode.toUpperCase()); if(params.language) query.set('language', params.language); if(params.tag) query.set('tag', params.tag); if(params.name) query.set('name', params.name); return cached(`stations:${query.toString()}`, 5*60_000, async()=>{ try { const res = await fetch(`${API_BASE}/stations/search?${query}`, { headers:{ 'User-Agent': UA }, next:{ revalidate: 300 } }); if(!res.ok) throw new Error(`Radio Browser ${res.status}`); const data = await res.json() as RadioBrowserStation[]; const stations = data.map(normalize).filter(s=>s.url && /^https?:\/\//i.test(s.url)).sort(sortStations); return stations.length ? stations : fallbackStations; } catch { return fallbackStations; } }); }

export async function fetchStationsByCountry(params: Record<string,string|undefined> = {}) { const code=params.countryCode?.toUpperCase() || aliases[(params.country || '').toLowerCase()]; const limit=params.limit ?? '50'; const offset=params.offset ?? '0'; const base = code ? `/stations/bycountrycodeexact/${encodeURIComponent(code)}` : `/stations/bycountry/${encodeURIComponent(params.country ?? '')}`; const query = new URLSearchParams({ hidebroken:'true', limit, offset, order:'votes', reverse:'true' }); if(params.tag) query.set('tag', params.tag); if(params.language) query.set('language', params.language); return cached(`country:${base}:${query.toString()}`, 5*60_000, async()=>{ try { const res=await fetch(`${API_BASE}${base}?${query}`, { headers:{ 'User-Agent': UA }, next:{ revalidate: 300 } }); if(!res.ok) throw new Error(`Radio Browser ${res.status}`); const data=await res.json() as RadioBrowserStation[]; return data.map(normalize).filter(s=>s.url && /^https?:\/\//i.test(s.url)).sort(sortStations); } catch { return fetchStations({ country:params.country, countryCode:code, limit, offset, tag:params.tag, language:params.language }); } }); }

export async function searchCountries(q = ''): Promise<CountryResult[]> { const query=q.trim().toLowerCase(); return cached(`countries:${query}`, 60*60_000, async()=>{ try { const res=await fetch(`${API_BASE}/countries`, { headers:{ 'User-Agent': UA }, next:{ revalidate: 3600 } }); if(!res.ok) throw new Error(`Radio Browser ${res.status}`); const data=await res.json() as RadioBrowserCountry[]; return data.filter(c=>c.name && c.iso_3166_1).map(c=>({ name:c.name!, code:c.iso_3166_1!.toUpperCase(), flag:flagFor(c.iso_3166_1), centroid:countryCentroids[c.iso_3166_1!.toUpperCase()] ?? {lat:20,lng:0}, station_count:c.stationcount ?? 0 })).filter(c=>!query || c.name.toLowerCase().includes(query) || c.code.toLowerCase()===query || aliases[query]===c.code).sort((a,b)=>b.station_count-a.station_count).slice(0,12); } catch { return Object.entries(aliases).filter(([name])=>!query || name.includes(query)).map(([name,code])=>({ name:name.replace(/\b\w/g,m=>m.toUpperCase()), code, flag:flagFor(code), centroid:countryCentroids[code] ?? {lat:20,lng:0}, station_count:0 })).slice(0,8); } }); }

export async function validateStream(url: string) { const started = Date.now(); const controller = new AbortController(); const timer = setTimeout(()=>controller.abort(), 7000); try { if(!/^https?:\/\//i.test(url)) throw new Error('Unsafe stream URL'); const res = await fetch(url, { method:'HEAD', signal:controller.signal, redirect:'follow' }); const type = res.headers.get('content-type') ?? ''; const playable = res.ok && /(audio|mpeg|ogg|aac|mp3|x-scpls|octet-stream)/i.test(type); return { is_active: playable, health_score: playable ? 90 : 35, response_time_ms: Date.now()-started, failure_count: playable ? 0 : 1, content_type:type, last_checked_at:new Date().toISOString() }; } catch { return { is_active:false, health_score:10, response_time_ms:Date.now()-started, failure_count:1, content_type:'unknown', last_checked_at:new Date().toISOString() }; } finally { clearTimeout(timer); } }
export function discoverIntent(query: string) { const q = query.toLowerCase(); const tags = ['gospel','jazz','news','talk','afrobeats','classical','reggae','sports','local','music']; return { country: Object.keys(aliases).find(c=>q.includes(c)), countryCode: Object.entries(aliases).find(([name])=>q.includes(name))?.[1], tag: tags.find(t=>q.includes(t)), language: q.includes('french')?'french':q.includes('english')?'english':undefined } as Record<string,string|undefined>; }
