import type { Station } from '../stations';

// Generated by scripts/discover-radio-stations.ts when RADIO_DISCOVERY_DRY_RUN=false.
// Keep this file schema-compatible with the existing WaveAtlas Station type.
export const discoveredRadioStations: Station[] = [];
