import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { candidateToStation, existingStationKeys, isDuplicateCandidate, normalizeUrl, qualityScore, rejectReason, type DiscoveryMetadata, type RadioBrowserCandidate } from '../lib/radio-discovery';
import { discoveredRadioStations } from '../lib/stations/discoveredRadioStations';
import { ariyoSeedStations } from '../lib/stations/ariyoSeedStations';
import { campusAtlasStations } from '../lib/stations/campusAtlasStations';

const API_BASE = process.env.RADIO_BROWSER_API_BASE ?? 'https://de1.api.radio-browser.info/json';
const USER_AGENT = process.env.RADIO_DISCOVERY_USER_AGENT ?? 'WaveAtlasGlobalRadioDiscovery/1.0 (https://github.com/Omoluabi1003/WaveAtlas)';
const DRY_RUN = process.env.RADIO_DISCOVERY_DRY_RUN !== 'false';
const MAX_ADD = Math.min(50, Math.max(0, Number(process.env.RADIO_DISCOVERY_MAX_ADD ?? '50')));
const PAGES = Math.max(1, Number(process.env.RADIO_DISCOVERY_PAGES ?? '2'));
const PAGE_SIZE = Math.min(500, Math.max(1, Number(process.env.RADIO_DISCOVERY_PAGE_SIZE ?? '100')));
const MIN_BITRATE = Number(process.env.RADIO_DISCOVERY_MIN_BITRATE ?? '128');
const REQUIRE_GEO = process.env.RADIO_DISCOVERY_REQUIRE_GEO !== 'false';
const SIGNAL_TIMEOUT_MS = Number(process.env.RADIO_DISCOVERY_SIGNAL_TIMEOUT_MS ?? '8000');

type ReportItem = { name?: string; url?: string; sourceStationUuid?: string; reason?: string; qualityScore?: number };
type Report = { generatedAt: string; dryRun: boolean; source: string; fetched: number; added: ReportItem[]; skipped: ReportItem[]; duplicate: ReportItem[]; failed: ReportItem[]; suspicious: ReportItem[] };
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function fetchCandidates() {
  const out: RadioBrowserCandidate[] = [];
  for (let page = 0; page < PAGES; page++) {
    const query = new URLSearchParams({ hidebroken: 'true', order: 'clicktrend', reverse: 'true', limit: String(PAGE_SIZE), offset: String(page * PAGE_SIZE) });
    const res = await fetch(`${API_BASE}/stations/search?${query}`, { headers: { 'User-Agent': USER_AGENT } });
    if (!res.ok) throw new Error(`Radio Browser returned ${res.status}`);
    out.push(...await res.json() as RadioBrowserCandidate[]);
    await sleep(Number(process.env.RADIO_DISCOVERY_RATE_LIMIT_MS ?? '1100'));
  }
  return out;
}

async function validateStream(url: string) {
  const headers = { 'User-Agent': USER_AGENT, Range: 'bytes=0-4095', Accept: '*/*' };
  const signal = AbortSignal.timeout(SIGNAL_TIMEOUT_MS);
  try {
    const head = await fetch(url, { method: 'HEAD', headers: { 'User-Agent': USER_AGENT }, redirect: 'follow', signal });
    if (head.ok || [401, 403, 405].includes(head.status)) return { ok: head.status < 500, status: head.status, resolvedUrl: head.url };
  } catch {}
  try {
    const get = await fetch(url, { method: 'GET', headers, redirect: 'follow', signal: AbortSignal.timeout(SIGNAL_TIMEOUT_MS) });
    return { ok: get.ok || get.status === 206, status: get.status, resolvedUrl: get.url };
  } catch (error) { return { ok: false, status: 0, error: error instanceof Error ? error.message : String(error) }; }
}

async function writeGenerated(stations: ReturnType<typeof candidateToStation>[], metadata: DiscoveryMetadata[]) {
  const file = 'lib/stations/discoveredRadioStations.ts';
  const metaFile = 'lib/stations/discoveredRadioMetadata.json';
  await writeFile(file, `import type { Station } from '../stations';\n\n// Generated by scripts/discover-radio-stations.ts. Do not edit manually.\nexport const discoveredRadioStations: Station[] = ${JSON.stringify(stations, null, 2)};\n`);
  await writeFile(metaFile, `${JSON.stringify(metadata, null, 2)}\n`);
}
async function writeReports(report: Report) {
  await mkdir('reports', { recursive: true });
  await writeFile('reports/radio-discovery-report.json', `${JSON.stringify(report, null, 2)}\n`);
  const md = [`# WaveAtlas Radio Discovery Report`, ``, `Generated: ${report.generatedAt}`, `Dry run: ${report.dryRun}`, `Source: ${report.source}`, ``, `| Bucket | Count |`, `| --- | ---: |`, `| Added | ${report.added.length} |`, `| Skipped | ${report.skipped.length} |`, `| Duplicate | ${report.duplicate.length} |`, `| Failed | ${report.failed.length} |`, `| Suspicious | ${report.suspicious.length} |`, ``, `## Added candidates`, ...report.added.map((i) => `- ${i.name} (${i.url}) score=${i.qualityScore}`), ``].join('\n');
  await writeFile('reports/radio-discovery-report.md', md);
}

async function main() {
  const generatedAt = new Date().toISOString();
  const report: Report = { generatedAt, dryRun: DRY_RUN, source: API_BASE, fetched: 0, added: [], skipped: [], duplicate: [], failed: [], suspicious: [] };
  const keys = existingStationKeys([...ariyoSeedStations, ...campusAtlasStations, ...discoveredRadioStations]);
  const accepted = [...discoveredRadioStations];
  const metadata: DiscoveryMetadata[] = JSON.parse(await readFile('lib/stations/discoveredRadioMetadata.json', 'utf8').catch(() => '[]'));
  let candidates: RadioBrowserCandidate[] = [];
  try {
    candidates = await fetchCandidates();
  } catch (error) {
    report.failed.push({ reason: `candidate_fetch_failed: ${error instanceof Error ? error.message : String(error)}` });
    await writeReports(report);
    console.log(`WaveAtlas radio discovery: added=0 skipped=0 duplicate=0 failed=${report.failed.length} suspicious=0 dryRun=${DRY_RUN}`);
    if (!DRY_RUN) process.exit(1);
    return;
  }
  report.fetched = candidates.length;
  for (const c of candidates) {
    const item = { name: c.name, url: c.url_resolved || c.url, sourceStationUuid: c.stationuuid, qualityScore: qualityScore(c) };
    const reason = rejectReason(c, MIN_BITRATE, REQUIRE_GEO);
    if (reason) { (reason === 'suspicious_name' ? report.suspicious : report.skipped).push({ ...item, reason }); continue; }
    if (isDuplicateCandidate(c, keys)) { report.duplicate.push({ ...item, reason: 'duplicate_existing_station' }); continue; }
    const signal = await validateStream(c.url_resolved || c.url || '');
    if (!signal.ok) { report.failed.push({ ...item, reason: `stream_validation_failed_${signal.status}` }); continue; }
    const station = candidateToStation({ ...c, url_resolved: signal.resolvedUrl || c.url_resolved }, generatedAt);
    accepted.push(station); keys.urls.add(normalizeUrl(station.url_resolved || station.url)); keys.names.add(station.normalized_name || ''); keys.sourceUuids.add(c.stationuuid || station.station_uuid);
    metadata.push({ stationUuid: station.station_uuid, discoverySource: 'radio-browser', sourceStationUuid: c.stationuuid || '', verifiedAt: generatedAt, lastSignalCheck: generatedAt, qualityScore: qualityScore(c), resolvedUrl: signal.resolvedUrl });
    report.added.push(item);
    if (report.added.length >= MAX_ADD) break;
  }
  await writeReports(report);
  if (!DRY_RUN && report.added.length) await writeGenerated(accepted, metadata);
  console.log(`WaveAtlas radio discovery: added=${report.added.length} skipped=${report.skipped.length} duplicate=${report.duplicate.length} failed=${report.failed.length} suspicious=${report.suspicious.length} dryRun=${DRY_RUN}`);
}

main().catch((error) => { console.error(error); process.exit(1); });
